Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      # # https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html
      # vbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]

      # vbox.memory = 8192
      # vbox.cpus = 2
    end

    config.vm.network "public_network"

    # Ubuntu 20.04 (Focal) VM
    config.vm.define "ivhost_ubuntu2004" do |ivhost|
      ivhost.vm.box = "generic/ubuntu2004"
      #ivhost.vm.box_version = "v4.3.8"
  
      # ivhost.vm.synced_folder ".", "/vagrant"
    end
  end
